function getElementById(id) {
    return document.getElementById(id);
}
export const menuOverlay = getElementById('menu-overlay');
export const deathOverlay = getElementById('death-overlay');
export const victoryOverlay = getElementById('victory-overlay');
export const startBtn = getElementById('start-btn');
export const restartBtn = getElementById('restart-btn');
export const winBtn = getElementById('win-btn');
export const nostrConnectBtn = getElementById('nostr-connect-btn');
export const nostrNsecInput = getElementById('nostr-nsec-input');
export const nostrNsecBtn = getElementById('nostr-nsec-btn');
export const nostrManualSection = getElementById('nostr-manual-section');
export const startLeaderboardList = getElementById('start-leaderboard-list');
export const startLeaderboardPanel = getElementById('start-leaderboard-panel');
export const startLeaderboardStatus = getElementById('start-leaderboard-status');
export const entryGateInvoiceOutput = getElementById('entry-invoice-output');
export const entryGatePanel = getElementById('entry-gate-panel');
export const entryGatePayBtn = getElementById('entry-pay-btn');
export const entryGateStatus = getElementById('entry-gate-status');
export const entryGateVerifyBtn = getElementById('entry-verify-btn');
export const jackpotValue = getElementById('jackpot-value');
export const healthVal = getElementById('health-value');
export const healthBar = getElementById('health-bar');
export const armorVal = getElementById('armor-value');
export const armorBar = getElementById('armor-bar');
export const zombieCountEl = getElementById('zombie-count');
export const ammoClipEl = getElementById('ammo-clip');
export const ammoReserveEl = getElementById('ammo-reserve');
export const feedbackMsg = getElementById('feedback-message');
export const crosshair = getElementById('crosshair');
export const damageFlash = getElementById('damage-flash');
export const bossHud = getElementById('boss-hud');
export const bossHealthFill = getElementById('boss-health-fill');
